version: '3'
services:
  oracle:
    image: store/oracle/database-enterprise:12.2.0.1-slim
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
    volumes:
      - ./oradata:/ORCL # persistent oracle database data.
